version: "3.8"

networks:
  project_network:
    driver: bridge

services:

  postgresql:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:latest
    hostname: ${PROJECT_NAME}_postgresql_host
    env_file:
      - ./.docker/postgresql/config.ini
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - project_network
    tty: true
    restart: unless-stopped

  pgadmin:
    container_name: ${PROJECT_NAME}-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgresql
    env_file:
      - ./.docker/pgadmin/config.ini
    ports:
      - 81:81
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - project_network
    links:
      - postgresql
    tty: true
    restart: unless-stopped
  
volumes:
  postgresql:
    driver: local
    name: ${PROJECT_NAME}_postgresql
  pgadmin:
    driver: local
    name: ${PROJECT_NAME}_pgadmin
  